name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: swen610
          POSTGRES_USER: swen610
          POSTGRES_PASSWORD: whowatchesthewatchmen
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Copy config file
        run: |
          cp config/gitlab-credentials.yml config/db.yml

      - name: Show Python version
        run: |
          python3 --version

      - name: Start server
        run: |
          python3 src/server.py &
          sleep 3

      - name: Run unit tests
        run: |
          python3 -m unittest discover -v
